use_frameworks!

target 'AppDevAnnouncements_Example' do
  pod 'AppDevAnnouncements', :path => '../'
  pod 'SnapKit'
  target 'AppDevAnnouncements_Tests' do
    inherit! :search_paths

    
  end
end
